# You will need Python 3.5 or newer
# install gTTs using the command prompt/terminal by executing the next command
# $ pip install gTTS


# Import the Gtts module for text to speech conversion 
from distutils import text_file
from gtts import gTTS 
  
# Import the tts_lang module to show all the languages that gTTS available
from gtts.lang import tts_langs

# import glob module to find the text file generated by downloadTxtMssg.js
# credits: https://stackoverflow.com/questions/1724693/find-a-file-in-python and https://pynative.com/python-glob/
import glob

#import subprocess to open a web browser
import subprocess

def select_language():
    # Shows all the languages available and check if the user choice is valid
    all_langs = tts_langs()
    print("\nPlease, select the language you want to use (Default = English):")

    for code, language in all_langs.items():
        print (code,":", language)
    
    # Initialize a variable to keep track of whether the user has already been prompted for a language selection
    prompted = False

    while True:
        if prompted:
            message = "\nSelect the language you want to use, write only two (2) letters: "
        else:
            message = "\nWrite only two (2) letters: " # Only shown the first time
        
        lang_selected=input(message)
        
        if lang_selected in all_langs:
            # Language is valid, exit the loop
            break
        else:
            print("\nLanguage not supported. Please make a right selection")
        
        # Set prompted to True to indicate that the user has already been prompted for a language selection
        prompted = True
    
    print("The language selected is:",all_langs[lang_selected])
    return lang_selected


def open_browser():
    # Ask the user if they want to open the website
    response = input("Do you want to open Whatsapp Web in a new tab? (y/n): ")
    if response.lower() == "y" or response.lower() == "yes":
        # Open the default browser and navigate to the specified website
        print("Opening Whatsapp Web in a new tab...")
        url = "https://web.whatsapp.com"
        subprocess.run(["cmd", "/c", "start", url])


def show_exit_mssg():
    input("\nPress <enter> to exit...")


def run():
    while True:
        try:
            # Reads the last text file, replacing the linebreaks to normal spaces for more clarity
            name_txt_file = glob.glob('../whaTxtMssg20*.txt',recursive=False)[-1] # It searches the file in the previous folder using relative path
            txt_file = open(name_txt_file,"rt", encoding='UTF-8')
            txt_mssg = txt_file.read().replace("\n", " ")
            break
        except IndexError:
            # Text file not found, ask the user if they want to try again
            print("\nThe text file with the Whatsapp text message was not found. Please make sure you have downloaded a Whatsapp text message")
            txt_file_not_found_response = input("Do you want to try again? (y/n): ")
            if txt_file_not_found_response.lower() == "n" or txt_file_not_found_response.lower() == "no":
                show_exit_mssg()
                return
            else:
                continue

    print("Text message found!")

    # Language we want to use 
    user_language= select_language()

    # Generates the audio file .mp3 and saves it with the same name as the text message
    audio_file = gTTS(text=txt_mssg, lang=user_language)
    name_audio_file = name_txt_file[0:-3:1]+"mp3" #It "changes" the extension of the file
    audio_file.save(name_audio_file)
    txt_file.close()

    # It only shows the name of the file withouth the relative path
    print(f"\nAudio file \"{name_audio_file[3::1]}\" generated correctly.")
    open_browser() # Ask the user to open the web browser to send the file
    show_exit_mssg()

if __name__ == '__main__':
    run()


''' # Play the converted file 
    os.system("start output.mp3")'''

# >>> import platform
    # >>> platform.system() https://stackoverflow.com/questions/1854/how-to-identify-on-which-os-python-is-running-on
    # 'Windows'


# read only the lines of a text file https://www.pythontutorial.net/python-basics/python-read-text-file/