# You will need Python 3.5 or newer
# install gTTs using the command prompt/terminal by executing the next command
# $ pip install gTTS


# Import the Gtts module for text to speech conversion 
from distutils import text_file
from gtts import gTTS 
  
# Import the tts_lang module to show all the languages that gTTS available
from gtts.lang import tts_langs

# import glob module to find the text file generated by downloadTxtMssg.js
# credits: https://stackoverflow.com/questions/1724693/find-a-file-in-python and https://pynative.com/python-glob/
import glob

#import subprocess to open a web browser
import subprocess

def select_language():
    # Shows all the languages available and check if the user choice is valid
    all_langs = tts_langs()
    print("\nPlease, select the language you want to use (Default = English):")

    for code, language in all_langs.items():
        print (code,":", language)
    
    # Initialize a variable to keep track of whether the user has already been prompted for a language selection
    prompted = False

    while True:
        if prompted:
            message = "\nSelect the language you want to use, write only two (2) letters: "
        else:
            message = "Write only two (2) letters: " # Only shown the first time
        
        lang_selected=input(message)
        
        if lang_selected in all_langs:
            # Language is valid, exit the loop
            break
        else:
            print("\nLanguage not supported. Please make a right selection")
        
        # Set prompted to True to indicate that the user has already been prompted for a language selection
        prompted = True
    
    print("The language selected is:",all_langs[lang_selected])
    return lang_selected


def open_browser():
    # Open the default browser and navigate to the specified website
    url = "https://web.whatsapp.com"
    subprocess.run(["cmd", "/c", "start", url])


def run():
    # Reads the last text file, replacing the linebreaks to normal spaces for more clarity
    name_txt_file = glob.glob('../whaTxtMssg202*.txt',recursive=False)[-1]
    txt_file = open(name_txt_file,"rt", encoding='UTF-8')
    txt_mssg = txt_file.read().replace("\n", " ")

    # Language we want to use 
    user_language= select_language()

    # Generates the audio file .mp3 and saves it with the same name as the text message
    audio_file = gTTS(text=txt_mssg, lang=user_language)
    name_audio_file = name_txt_file[0:-3:1]+"mp3" #It "changes" the extension of the file
    audio_file.save(name_audio_file)
    txt_file.close()

    input(f"Audio file \"{name_audio_file}\" generated correctly.\nPress <enter> to exit...")
    open_browser() # Opens the web browser to send the file

if __name__ == '__main__':
    run()


'''
    # Play the converted file 
    os.system("start output.mp3")'''

# >>> import platform
    # >>> platform.system() https://stackoverflow.com/questions/1854/how-to-identify-on-which-os-python-is-running-on
    # 'Windows'


# read only the lines of a text file https://www.pythontutorial.net/python-basics/python-read-text-file/